--------------------------------------------------------
--  DDL for View RLY_COMM_TEMP_ACCT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RLY_COMM_TEMP_ACCT" ("ID_RECORD", "TEMPLATE_NAME", "DESCRIPTION", "OBJ_OWNER", "OBJECT_NAME", "SEND_FROM_EMAIL", "REPLY_TO_EMAIL", "SUBJECT_LINE", "MESSAGE_BODY_PT", "MESSAGE_BODY_HTML", "ID_CHECK_STAMP", "ACCT_ID", "AUTH_ID", "ID_ROW") AS 
  SELECT "ID_RECORD","TEMPLATE_NAME","DESCRIPTION","OBJ_OWNER","OBJECT_NAME","SEND_FROM_EMAIL","REPLY_TO_EMAIL","SUBJECT_LINE","MESSAGE_BODY_PT","MESSAGE_BODY_HTML","ID_CHECK_STAMP","ACCT_ID","AUTH_ID","ID_ROW"
  FROM
    relay_comm_template_acct
;
