-- Generated by Oracle SQL Developer REST Data Services 19.4.0.354.1759
-- Exported REST Definitions from ORDS Schema Version 19.4.1.r0572045
-- Schema: RELAY   Date: Wed Mar 11 15:21:40 EDT 2020
--
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'RELAY',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'relay',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'v1',
      p_base_path      => '/v1/',
      p_items_per_page =>  50,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/assignment',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/assignment',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.assignment.list'' a
  ,i.id_assignee b
  ,i.code_status c
  ,i.priority d
  ,i.assignment e
  ,i.node_type f
  ,i.ind_decision g
  ,i.person_code h
  ,i.id_assignment i
  ,i.process_name j
  ,i.id_process k
  ,q.id_request l
FROM
   vw_assign_inbox i
  ,rly_person_acct p
  ,rly_fqueue_acct q
WHERE 1=1
  and i.person_code = p.person_code
  and q.id_record = i.id_instance
  and lower(i.person_code) like ''%''||lower(:person_code)||''%''
  and q.acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''1'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/assignment',
      p_method             => 'GET',
      p_name               => 'person_code',
      p_bind_variable_name => 'person_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/object',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/object',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select
  ''rly.object.list'' a,
  obj_name b,
  ind_active c,
  description d
from
  rly_obj_acct
where 1=1 
  and ind_active = 1
  and obj_name like ''%''||:object_name||''%''
  and ind_active like ''%''||:ind_active||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''2'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/object',
      p_method             => 'GET',
      p_name               => 'ind_active',
      p_bind_variable_name => 'ind_active',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/object',
      p_method             => 'GET',
      p_name               => 'object_name',
      p_bind_variable_name => 'object_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/object.attribute',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/object.attribute',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select
  ''rly.object.attribute.list'' a,
  a.attr_name b,
  a.attr_type c,
  a.seq_id d,
  a.ind_upd e,
  a.ind_key f
from
  rly_obj_attr_acct a
 ,rly_obj_acct o
where a.id_object = o.id_record
  and lower(o.obj_name) = lower(:object_name)
  and o.acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''3'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/object.attribute',
      p_method             => 'GET',
      p_name               => 'object_name',
      p_bind_variable_name => 'object_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/process',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/process',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select
  ''rly.process.list'' a,
  process_name b,
  description c,
  proc_revision d,
  id_role e,
  obj_name f,
  ind_enabled g,
  ind_active h,
  ind_allow_more_inst i,
  (select count(*) 
   from rly_fqueue_acct 
   where flow_name = p.process_name 
     and node_type != ''CLOSED'' 
     and internal_id like case when :internal_id is not null 
                               then :internal_id else ''%'' end) j
from
  rly_process_acct p
where 1=1 
  and lower(process_name) like ''%''||lower(:process_name)||''%''
  and ind_enabled like ''%''||:ind_enabled||''%''
  and ind_active like ''%''||:ind_active||''%''
  and lower(obj_name) like ''%''||lower(:object_name)||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''4'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/process',
      p_method             => 'GET',
      p_name               => 'ind_active',
      p_bind_variable_name => 'ind_active',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/process',
      p_method             => 'GET',
      p_name               => 'ind_enabled',
      p_bind_variable_name => 'ind_enabled',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/process',
      p_method             => 'GET',
      p_name               => 'internal_id',
      p_bind_variable_name => 'internal_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/process',
      p_method             => 'GET',
      p_name               => 'object_name',
      p_bind_variable_name => 'object_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/process',
      p_method             => 'GET',
      p_name               => 'process_name',
      p_bind_variable_name => 'process_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.list'' a,
  id_request b,
  internal_id c,
  flow_name d,
  obj_name e,
  node_type f,
  change_id g,
  timelimit h,
  ind_condition i,
  (select count(*) from tk_vw_inst_data where id_instance = a.id_record) j,
  (select count(*) from tk_vw_inst_vars where id_instance = a.id_record) k,
  (select count(*) from rly_wf_rec_acct where id_instance = a.id_record) l,
  (select count(*) from vw_assign_inbox where id_instance = a.id_record) m,
  (select count(*) from vw_desc_node_links where id_instance = a.id_record) n,
  case when node_type = ''CLOSED'' then 1 else 0 end o
FROM
  rly_fqueue_acct a
WHERE 1=1
  and lower(id_request) like ''%''||lower(:request_id)||''%''
  and lower(obj_name) like ''%''||lower(:object_name)||''%''
  and lower(internal_id) like ''%''||lower(:internal_id)||''%''
  and lower(flow_name) like ''%''||lower(:flow_name)||''%''
  and lower(node_type) like ''%''||lower(:node_type)||''%''
  and lower(change_id) like ''%''||lower(:change_id)||''%''
  and case when node_type = ''CLOSED'' then 1 else 0 end 
      = nvl(:ind_closed,case when node_type = ''CLOSED'' then 1 else 0 end)
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''5'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue',
      p_method             => 'GET',
      p_name               => 'change_id',
      p_bind_variable_name => 'change_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue',
      p_method             => 'GET',
      p_name               => 'flow_name',
      p_bind_variable_name => 'flow_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue',
      p_method             => 'GET',
      p_name               => 'ind_closed',
      p_bind_variable_name => 'ind_closed',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue',
      p_method             => 'GET',
      p_name               => 'internal_id',
      p_bind_variable_name => 'internal_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue',
      p_method             => 'GET',
      p_name               => 'node_type',
      p_bind_variable_name => 'node_type',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue',
      p_method             => 'GET',
      p_name               => 'object_name',
      p_bind_variable_name => 'object_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.assignment',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.assignment',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.assignment'' a
  ,i.id_assignee b
  ,i.code_status c
  ,i.priority d
  ,i.assignment e
  ,i.node_type f
  ,i.ind_decision g
  ,i.person_code h
  ,a.id_request i
FROM
   rly_fqueue_acct a
  ,vw_assign_inbox i
WHERE 1=1
  and i.id_instance = a.id_record
  and lower(id_request) like ''%''||lower(:request_id)||''%''
  and lower(person_code) = nvl(lower(:person_code),lower(person_code))
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''6'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue.assignment',
      p_method             => 'GET',
      p_name               => 'person_code',
      p_bind_variable_name => 'person_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue.assignment',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.choices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.choices',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.choice'' a
  ,l.id_link b
  ,l.description c
  ,l.sequence d
  ,l.ind_link_cond e
  ,a.id_request f
FROM
   rly_fqueue_acct a
  ,vw_desc_node_links l
WHERE 1=1
  and l.id_instance = a.id_record
  and lower(id_request) like ''%''||lower(:request_id)||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''7'') = 1
order by l.sequence'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue.choices',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.data',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.data',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.data.list'' a,
  var_type b,
  var_name c,
  var_value d,
  var_sequence e,
  nvl(ind_changed,0) f
  ,q.id_request g
FROM 
   tk_vw_inst_data a
  ,rly_fqueue_acct q
WHERE 1=1
  and a.id_instance = q.id_record
  and lower(id_request) = lower(:request_id)
  and q.acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''8'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue.data',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.history',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.history',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.history.list'' a,
  a.id_record b,
  id_workflow_run c,
  record_type d,
  record_subtype e,
  relay_p_anydata.f_date_to_epoch(date_record) f,
  id_proc_rec g,
  id_child_rec h
  ,q.id_request i
FROM 
   rly_wf_rec_acct a
  ,rly_fqueue_acct q
WHERE 1=1
  and a.id_instance = q.id_record
  and lower(q.id_request) = lower(:request_id)
  and q.acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''9'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue.history',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.variables',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/queue.variables',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.variable.list'' a,
  var_type b,
  var_name c,
  var_value d,
  var_sequence e,
  nvl(ind_changed,0) f
  ,q.id_request g
FROM 
   tk_vw_inst_vars a
  ,rly_fqueue_acct q
WHERE 1=1
  and a.id_instance = q.id_record
  and lower(id_request) = lower(:request_id)
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''10'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/queue.variables',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/resource.group',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/resource.group',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.resource.group.list'' a,
  group_name b,
  description c,
  group_status d,
  members e
FROM
  rly_persgrp_acct p
WHERE 1=1 
  and lower(group_name) like ''%''||lower(:group_name)||''%''
  and lower(group_status) like ''%''||lower(:group_status)||''%''
  and lower(description) like ''%''||lower(:description)||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''11'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.group',
      p_method             => 'GET',
      p_name               => 'description',
      p_bind_variable_name => 'description',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.group',
      p_method             => 'GET',
      p_name               => 'group_name',
      p_bind_variable_name => 'group_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.group',
      p_method             => 'GET',
      p_name               => 'group_status',
      p_bind_variable_name => 'group_status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/resource.member',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/resource.member',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.resource.group.member.list'' a,
  group_name b,
  member_sequence c,
  ind_group_default d,
  id_group_member e,
  (select first_name||'' ''||last_name||'' (''||person_code||'')'' grp_member
   from rly_person_acct 
   where id_record = gm.id_group_member) f
FROM rly_grpmbr_acct gm
WHERE lower(group_name) = lower(:group_name)
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''12'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.member',
      p_method             => 'GET',
      p_name               => 'group_name',
      p_bind_variable_name => 'group_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/resource.person',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'abstract/resource.person',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.resource.person.list'' a,
  person_code b,
  status c,
  display_name d,
  first_name e,
  last_name f,
  relay_p_anydata.f_date_to_epoch(date_status) g,
  email_address h,
  (select count(*) from rly_grpmbr_acct where id_group_member = p.id_record) i
FROM
  rly_person_acct p
WHERE 1=1 
  and lower(person_code) like ''%''||lower(:person_code)||''%''
  and lower(status) like ''%''||lower(:status)||''%''
  and lower(first_name) like ''%''||lower(:first_name)||''%''
  and lower(last_name) like ''%''||lower(:last_name)||''%''
  and lower(email_address) like ''%''||lower(:email)||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''13'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.person',
      p_method             => 'GET',
      p_name               => 'email',
      p_bind_variable_name => 'email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.person',
      p_method             => 'GET',
      p_name               => 'first_name',
      p_bind_variable_name => 'first_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.person',
      p_method             => 'GET',
      p_name               => 'last_name',
      p_bind_variable_name => 'last_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.person',
      p_method             => 'GET',
      p_name               => 'person_code',
      p_bind_variable_name => 'person_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'abstract/resource.person',
      p_method             => 'GET',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/assignment',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/assignment',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.assignment.list'' web_service_id
  ,i.id_assignee 
  ,i.code_status 
  ,i.priority 
  ,i.assignment 
  ,i.node_type 
  ,i.ind_decision 
  ,i.person_code 
  ,i.id_assignment 
  ,i.process_name 
  ,i.id_process 
  ,q.id_request 
FROM
   vw_assign_inbox i
  ,rly_person_acct p
  ,rly_fqueue_acct q
WHERE 1=1
  and i.person_code = p.person_code
  and q.id_record = i.id_instance
  and lower(i.person_code) like ''%''||lower(:person_code)||''%''
  and q.acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''14'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/assignment',
      p_method             => 'GET',
      p_name               => 'person_code',
      p_bind_variable_name => 'person_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/object',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/object',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select
  ''rly.object.list'' web_service_id,
  obj_name ,
  ind_active ,
  description 
from
  rly_obj_acct
where 1=1 
  and ind_active = 1
  and obj_name like ''%''||:object_name||''%''
  and ind_active like ''%''||:ind_active||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''15'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/object',
      p_method             => 'GET',
      p_name               => 'ind_active',
      p_bind_variable_name => 'ind_active',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/object',
      p_method             => 'GET',
      p_name               => 'object_name',
      p_bind_variable_name => 'object_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/object.attribute',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/object.attribute',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select
  ''rly.object.attribute.list'' web_service_id,
  a.attr_name,
  a.attr_type,
  a.seq_id,
  a.ind_upd,
  a.ind_key
from
  rly_obj_attr_acct a
 ,rly_obj_acct o
where a.id_object = o.id_record
  and lower(o.obj_name) = lower(:object_name)
  and o.acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''16'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/object.attribute',
      p_method             => 'GET',
      p_name               => 'object_name',
      p_bind_variable_name => 'object_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/process',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/process',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select
  ''rly.process.list'' web_service_id,
  process_name,
  description ,
  proc_revision ,
  id_role ,
  obj_name ,
  ind_enabled ,
  ind_active ,
  ind_allow_more_inst ,
  (select count(*) 
   from rly_fqueue_acct 
   where flow_name = p.process_name 
     and node_type != ''CLOSED'' 
     and internal_id like case when :internal_id is not null 
                               then :internal_id else ''%'' end) open_instances
from
  rly_process_acct p
where 1=1 
  and lower(process_name) like ''%''||lower(:process_name)||''%''
  and ind_enabled like ''%''||:ind_enabled||''%''
  and ind_active like ''%''||:ind_active||''%''
  and lower(obj_name) like ''%''||lower(:object_name)||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''17'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/process',
      p_method             => 'GET',
      p_name               => 'ind_active',
      p_bind_variable_name => 'ind_active',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/process',
      p_method             => 'GET',
      p_name               => 'ind_enabled',
      p_bind_variable_name => 'ind_enabled',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/process',
      p_method             => 'GET',
      p_name               => 'internal_id',
      p_bind_variable_name => 'internal_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/process',
      p_method             => 'GET',
      p_name               => 'object_name',
      p_bind_variable_name => 'object_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/process',
      p_method             => 'GET',
      p_name               => 'process_name',
      p_bind_variable_name => 'process_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.list'' web_service_id,
  id_request ,
  internal_id ,
  flow_name ,
  obj_name ,
  node_type ,
  change_id ,
  timelimit ,
  ind_condition ,
  (select count(*) from tk_vw_inst_data where id_instance = a.id_record) data,
  (select count(*) from tk_vw_inst_vars where id_instance = a.id_record) vars,
  (select count(*) from rly_wf_rec_acct where id_instance = a.id_record) hist,
  (select count(*) from vw_assign_inbox where id_instance = a.id_record) assign,
  (select count(*) from vw_desc_node_links where id_instance = a.id_record) opts,
  case when node_type = ''CLOSED'' then 1 else 0 end ind_closed
FROM
  rly_fqueue_acct a
WHERE 1=1
  and lower(id_request) like ''%''||lower(:request_id)||''%''
  and lower(obj_name) like ''%''||lower(:object_name)||''%''
  and lower(internal_id) like ''%''||lower(:internal_id)||''%''
  and lower(flow_name) like ''%''||lower(:flow_name)||''%''
  and lower(node_type) like ''%''||lower(:node_type)||''%''
  and lower(change_id) like ''%''||lower(:change_id)||''%''
  and case when node_type = ''CLOSED'' then 1 else 0 end 
      = nvl(:ind_closed,case when node_type = ''CLOSED'' then 1 else 0 end)
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''18'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue',
      p_method             => 'GET',
      p_name               => 'change_id',
      p_bind_variable_name => 'change_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue',
      p_method             => 'GET',
      p_name               => 'flow_name',
      p_bind_variable_name => 'flow_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue',
      p_method             => 'GET',
      p_name               => 'internal_id',
      p_bind_variable_name => 'internal_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue',
      p_method             => 'GET',
      p_name               => 'node_type',
      p_bind_variable_name => 'node_type',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue',
      p_method             => 'GET',
      p_name               => 'object_name',
      p_bind_variable_name => 'object_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.assignment',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.assignment',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.assignment'' web_service_id
  ,i.id_assignee 
  ,i.code_status 
  ,i.priority 
  ,i.assignment 
  ,i.node_type 
  ,i.ind_decision 
  ,i.person_code 
  ,a.id_request
FROM
   rly_fqueue_acct a
  ,vw_assign_inbox i
WHERE 1=1
  and i.id_instance = a.id_record
  and lower(id_request) like ''%''||lower(:request_id)||''%''
  and lower(person_code) = nvl(lower(:person_code),lower(person_code))
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''19'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue.assignment',
      p_method             => 'GET',
      p_name               => 'person_code',
      p_bind_variable_name => 'person_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue.assignment',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.choices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.choices',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.choice'' web_service_id
  ,l.id_link 
  ,l.description 
  ,l.sequence 
  ,l.ind_link_cond 
  ,a.id_request
FROM
   rly_fqueue_acct a
  ,vw_desc_node_links l
WHERE 1=1
  and l.id_instance = a.id_record
  and lower(id_request) like ''%''||lower(:request_id)||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''20'') = 1
order by l.sequence'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue.choices',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.data',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.data',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.data.list'' web_service_id,
  var_type ,
  var_name ,
  var_value ,
  var_sequence ,
  nvl(ind_changed,0) ind_changed
  ,q.id_request
FROM 
   tk_vw_inst_data a
  ,rly_fqueue_acct q
WHERE 1=1
  and a.id_instance = q.id_record
  and lower(id_request) = lower(:request_id)
  and q.acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''21'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue.data',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.history',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.history',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.history.list'' web_service_id,
  a.id_record ,
  id_workflow_run ,
  record_type ,
  record_subtype ,
  relay_p_anydata.f_date_to_epoch(date_record) date_record,
  id_proc_rec ,
  id_child_rec 
  ,q.id_request
FROM 
   rly_wf_rec_acct a
  ,rly_fqueue_acct q
WHERE 1=1
  and a.id_instance = q.id_record
  and lower(q.id_request) = lower(:request_id)
  and q.acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''22'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue.history',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.variables',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/queue.variables',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.queue.variable.list'' web_service_id,
  var_type ,
  var_name ,
  var_value ,
  var_sequence ,
  nvl(ind_changed,0) ind_changed
  ,q.id_request
FROM 
   tk_vw_inst_vars a
  ,rly_fqueue_acct q
WHERE 1=1
  and a.id_instance = q.id_record
  and lower(id_request) = lower(:request_id)
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''23'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/queue.variables',
      p_method             => 'GET',
      p_name               => 'request_id',
      p_bind_variable_name => 'request_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/resource.group',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/resource.group',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.resource.group.list'' web_service_id,
  group_name ,
  description ,
  group_status ,
  members 
FROM
  rly_persgrp_acct p
WHERE 1=1 
  and lower(group_name) like ''%''||lower(:group_name)||''%''
  and lower(group_status) like ''%''||lower(:group_status)||''%''
  and lower(description) like ''%''||lower(:description)||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''24'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.group',
      p_method             => 'GET',
      p_name               => 'description',
      p_bind_variable_name => 'description',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.group',
      p_method             => 'GET',
      p_name               => 'group_name',
      p_bind_variable_name => 'group_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.group',
      p_method             => 'GET',
      p_name               => 'group_status',
      p_bind_variable_name => 'group_status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/resource.member',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/resource.member',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.resource.group.member.list'' web_service_id,
  group_name ,
  member_sequence ,
  ind_group_default ,
  id_group_member ,
  (select first_name||'' ''||last_name||'' (''||person_code||'')'' grp_member
   from rly_person_acct 
   where id_record = gm.id_group_member) member_name
FROM rly_grpmbr_acct gm
WHERE lower(group_name) = lower(:group_name)
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''25'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.member',
      p_method             => 'GET',
      p_name               => 'group_name',
      p_bind_variable_name => 'group_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1',
      p_pattern        => 'simple/resource.person',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1',
      p_pattern        => 'simple/resource.person',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
  ''rly.resource.person.list'' web_service_id,
  person_code ,
  status ,
  display_name ,
  first_name ,
  last_name ,
  relay_p_anydata.f_date_to_epoch(date_status) date_status ,
  email_address ,
  (select count(*) from rly_grpmbr_acct where id_group_member = p.id_record) group_members
FROM
  rly_person_acct p
WHERE 1=1 
  and lower(person_code) like ''%''||lower(:person_code)||''%''
  and lower(status) like ''%''||lower(:status)||''%''
  and lower(first_name) like ''%''||lower(:first_name)||''%''
  and lower(last_name) like ''%''||lower(:last_name)||''%''
  and lower(email_address) like ''%''||lower(:email)||''%''
  and acct_id = (select NAME 
                 from user_ords_clients 
                 where client_id = :current_user)
  and tk_p_api.f_wsc(''26'') = 1'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.person',
      p_method             => 'GET',
      p_name               => 'email',
      p_bind_variable_name => 'email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.person',
      p_method             => 'GET',
      p_name               => 'first_name',
      p_bind_variable_name => 'first_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.person',
      p_method             => 'GET',
      p_name               => 'last_name',
      p_bind_variable_name => 'last_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.person',
      p_method             => 'GET',
      p_name               => 'person_code',
      p_bind_variable_name => 'person_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'v1',
      p_pattern            => 'simple/resource.person',
      p_method             => 'GET',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      

  ORDS.CREATE_ROLE(p_role_name  => 'relay_user');

  l_roles(1)   := 'oracle.dbtools.autorest.any.schema';
  l_roles(2)   := 'relay_user';
  l_modules(1) := 'v1';
  l_patterns(1):= '/metadata-catalog/programs/*';
  l_patterns(2):= '/programs/*';
  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'relay_iface',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => '',
      p_description    => '',
      p_comments       => NULL);      

	
  oauth.create_client(
      p_name => relay_p_anydata.f_get_param_vc2('ACCT_ID'),
      p_description => 'RELAY BASE CLIENT',
      p_grant_type => 'client_credentials',
      p_privilege_names => 'relay_iface',
      p_support_email => 'relay_wf@outlook.com');
  
  
  COMMIT; 

END;