--------------------------------------------------------
--  DDL for Table AWF_PERSON
--------------------------------------------------------

  CREATE TABLE "AWF_PERSON" 
   (	"ID_RECORD" NUMBER, 
	"PERSON_CODE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"DISPLAY_NAME" VARCHAR2(200 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"ID_DELEGATE" NUMBER, 
	"DATE_DELAGATE_START" DATE, 
	"DATE_DELEGATE_END" DATE, 
	"DATE_STATUS" DATE, 
	"EMAIL_ADDRESS" VARCHAR2(250 BYTE), 
	"ID_CHECK_STAMP" NUMBER
   ) ;
