--------------------------------------------------------
--  DDL for Table AWF_D2D_DATA
--------------------------------------------------------

  CREATE TABLE "AWF_D2D_DATA" 
   (	"ID_RECORD" NUMBER, 
	"ID_CHECK_STAMP" NUMBER, 
	"TYPE_RECORD" VARCHAR2(100 BYTE), 
	"ID_SHAPE" NUMBER, 
	"ID_PORT" NUMBER, 
	"PORT_SEQ" NUMBER, 
	"LINK_TYPE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(500 BYTE), 
	"ID" VARCHAR2(500 BYTE), 
	"X" NUMBER, 
	"Y" NUMBER, 
	"WIDTH" NUMBER DEFAULT 10, 
	"HEIGHT" NUMBER DEFAULT 10, 
	"ALPHA" NUMBER DEFAULT 1, 
	"ANGLE" NUMBER DEFAULT 0, 
	"USERDATA" CLOB, 
	"CSSCLASS" VARCHAR2(500 BYTE), 
	"BGCOLOR" VARCHAR2(20 BYTE), 
	"COLOR" VARCHAR2(20 BYTE), 
	"STROKE" NUMBER DEFAULT 1, 
	"DASHARRAY" VARCHAR2(20 BYTE) DEFAULT null, 
	"MAXFANOUT" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"PORT" VARCHAR2(20 BYTE), 
	"LOCATOR" VARCHAR2(500 BYTE), 
	"RADIUS" NUMBER, 
	"IND_IS_POSITIVE" NUMBER(1,0), 
	"PATH" VARCHAR2(1000 BYTE), 
	"SHAPE_TYPE" VARCHAR2(100 BYTE), 
	"ROUTER" VARCHAR2(500 BYTE), 
	"POLICY" VARCHAR2(500 BYTE), 
	"OUTLINECOLOR" VARCHAR2(20 BYTE), 
	"OUTLINESTROKE" NUMBER
   ) ;
