--------------------------------------------------------
--  DDL for Table AWF_USERS
--------------------------------------------------------

  CREATE TABLE "AWF_USERS" 
   (	"ID_RECORD" NUMBER, 
	"ID_CHECK_STAMP" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"USER_PW" VARCHAR2(1000 BYTE), 
	"USER_STATUS" VARCHAR2(20 BYTE) DEFAULT 'NEW', 
	"USER_EMAIL" VARCHAR2(1000 BYTE), 
	"LOGIN_FAILURES" NUMBER DEFAULT 0, 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"IND_ADMIN" NUMBER DEFAULT 0, 
	"IND_OWNER" NUMBER
   ) ;

   COMMENT ON COLUMN "AWF_USERS"."USER_STATUS" IS 'NEW / ACTIVE / BLOCKED';
