
  CREATE TABLE "RLY_DEV02"."TK_OBJ_ATTR" 
   (	"ID_RECORD" NUMBER DEFAULT "RLY_DEV02"."TK_IFACE_MAIN"."NEXTVAL", 
	"ID_OBJECT" NUMBER, 
	"ATTR_NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ATTR_TYPE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SEQ_ID" NUMBER, 
	"IND_UPD" NUMBER, 
	"IND_KEY" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 